print("Hello")
print("My name is Aniket Kumar")
print("I belongs to Farrukhabad")
print("My Father name is Mr. Nitin Kumar")
print("My Mother name is Mrs. Chandni")
print("I am studying in Btech(CSE) GLA University in Mathura")